/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/HolidayManager.ts
var HolidayManager_exports = {};
__export(HolidayManager_exports, {
  HolidayManager: () => HolidayManager,
  HolidayType: () => HolidayType,
  holidayManager: () => holidayManager
});
var HolidayType, BUILTIN_HOLIDAYS, HolidayManager, holidayManager;
var init_HolidayManager = __esm({
  "src/HolidayManager.ts"() {
    HolidayType = /* @__PURE__ */ ((HolidayType2) => {
      HolidayType2["LEGAL"] = "legal";
      HolidayType2["WORKDAY"] = "workday";
      HolidayType2["WEEKEND"] = "weekend";
      HolidayType2["NORMAL"] = "normal";
      return HolidayType2;
    })(HolidayType || {});
    BUILTIN_HOLIDAYS = {
      2024: [
        // 元旦
        { date: "2024-01-01", name: "\u5143\u65E6", type: "legal" /* LEGAL */, isOff: true },
        // 春节
        { date: "2024-02-09", name: "\u9664\u5915", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-02-10", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-02-11", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-02-12", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-02-13", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-02-14", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-02-15", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-02-16", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-02-17", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 春节调休上班
        { date: "2024-02-04", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2024-02-18", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 清明节
        { date: "2024-04-04", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-04-05", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-04-06", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 劳动节
        { date: "2024-05-01", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-05-02", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-05-03", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-05-04", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-05-05", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 劳动节调休上班
        { date: "2024-04-28", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2024-05-11", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 端午节
        { date: "2024-06-10", name: "\u7AEF\u5348\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 中秋节
        { date: "2024-09-15", name: "\u4E2D\u79CB\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-09-16", name: "\u4E2D\u79CB\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-09-17", name: "\u4E2D\u79CB\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 中秋节调休上班
        { date: "2024-09-14", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 国庆节
        { date: "2024-10-01", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-10-02", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-10-03", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-10-04", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-10-05", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-10-06", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2024-10-07", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 国庆节调休上班
        { date: "2024-09-29", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2024-10-12", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false }
      ],
      2025: [
        { date: "2025-01-01", name: "\u5143\u65E6", type: "legal" /* LEGAL */, isOff: true },
        // 春节
        { date: "2025-01-28", name: "\u9664\u5915", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-01-29", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-01-30", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-01-31", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-02-01", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-02-02", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-02-03", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-02-04", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-01-26", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2025-02-08", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 清明节
        { date: "2025-04-04", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-04-05", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-04-06", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 劳动节
        { date: "2025-05-01", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-05-02", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-05-03", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-05-04", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-05-05", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-04-27", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 端午节
        { date: "2025-05-31", name: "\u7AEF\u5348\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-06-01", name: "\u7AEF\u5348\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-06-02", name: "\u7AEF\u5348\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 国庆节、中秋节（2025年重合）
        { date: "2025-10-01", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-10-02", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-10-03", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-10-04", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-10-05", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-10-06", name: "\u56FD\u5E86\u8282/\u4E2D\u79CB\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-10-07", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-10-08", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2025-09-28", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2025-10-11", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false }
      ],
      2026: [
        { date: "2026-01-01", name: "\u5143\u65E6", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-01-02", name: "\u5143\u65E6", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-01-03", name: "\u5143\u65E6", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-01-04", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 春节
        { date: "2026-02-17", name: "\u9664\u5915", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-02-18", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-02-19", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-02-20", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-02-21", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-02-22", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-02-23", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-02-24", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-02-15", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2026-02-28", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 清明节
        { date: "2026-04-04", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-04-05", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-04-06", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 劳动节
        { date: "2026-05-01", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-05-02", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-05-03", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-05-04", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-05-05", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-04-26", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2026-05-09", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 端午节
        { date: "2026-06-19", name: "\u7AEF\u5348\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-06-20", name: "\u7AEF\u5348\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-06-21", name: "\u7AEF\u5348\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 中秋节
        { date: "2026-09-25", name: "\u4E2D\u79CB\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-09-26", name: "\u4E2D\u79CB\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-09-27", name: "\u4E2D\u79CB\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 国庆节
        { date: "2026-10-01", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-10-02", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-10-03", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-10-04", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-10-05", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-10-06", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-10-07", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-10-08", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-09-20", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2026-10-10", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false }
      ],
      2027: [
        { date: "2027-01-01", name: "\u5143\u65E6", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-01-02", name: "\u5143\u65E6", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-01-03", name: "\u5143\u65E6", type: "legal" /* LEGAL */, isOff: true },
        { date: "2026-12-31", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2027-01-09", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 春节
        { date: "2027-02-06", name: "\u9664\u5915", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-02-07", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-02-08", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-02-09", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-02-10", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-02-11", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-02-12", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-02-13", name: "\u6625\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-02-05", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2027-02-20", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 清明节
        { date: "2027-04-03", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-04-04", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-04-05", name: "\u6E05\u660E\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 劳动节
        { date: "2027-05-01", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-05-02", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-05-03", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-05-04", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-05-05", name: "\u52B3\u52A8\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-04-25", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2027-05-08", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 端午节
        { date: "2027-06-09", name: "\u7AEF\u5348\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-06-10", name: "\u7AEF\u5348\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-06-11", name: "\u7AEF\u5348\u8282", type: "legal" /* LEGAL */, isOff: true },
        // 中秋节
        { date: "2027-09-15", name: "\u4E2D\u79CB\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-09-16", name: "\u4E2D\u79CB\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-09-17", name: "\u4E2D\u79CB\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-09-12", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2027-09-26", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        // 国庆节
        { date: "2027-10-01", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-10-02", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-10-03", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-10-04", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-10-05", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-10-06", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-10-07", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-10-08", name: "\u56FD\u5E86\u8282", type: "legal" /* LEGAL */, isOff: true },
        { date: "2027-09-19", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false },
        { date: "2027-10-09", name: "\u73ED", type: "workday" /* WORKDAY */, isOff: false }
      ]
    };
    HolidayManager = class {
      constructor() {
        /** 按年份索引的缓存数据 */
        this.cache = /* @__PURE__ */ new Map();
        this.loadBuiltinData();
      }
      /**
       * 加载内置节假日数据到内存缓存
       */
      loadBuiltinData() {
        for (const [year, holidays] of Object.entries(BUILTIN_HOLIDAYS)) {
          this.cache.set(parseInt(year), [...holidays]);
        }
      }
      // ── 查询方法 ────────────────────────────
      /**
       * 获取指定日期的节假日信息
       *
       * @param date - 要查询的日期
       * @returns 节假日信息对象，无匹配返回 undefined
       */
      getHolidayInfo(date) {
        const dateStr = this.formatDate(date);
        const year = date.getFullYear();
        const holidays = this.cache.get(year) || [];
        return holidays.find((h) => h.date === dateStr);
      }
      /**
       * 获取指定年份的全部节假日数据
       *
       * @param year - 年份
       * @returns 该年的所有特殊日期记录
       */
      getYearHolidays(year) {
        return this.cache.get(year) || [];
      }
      /**
       * 判断是否为法定节假日
       *
       * @param date - 日期
       * @returns 是否为法定节假日（且放假）
       */
      isHoliday(date) {
        const info = this.getHolidayInfo(date);
        return (info == null ? void 0 : info.type) === "legal" /* LEGAL */ && info.isOff;
      }
      /**
       * 判断是否为调休上班日
       *
       * @param date - 日期
       * @returns 是否需要上班的调休日
       */
      isWorkday(date) {
        const info = this.getHolidayInfo(date);
        return (info == null ? void 0 : info.type) === "workday" /* WORKDAY */;
      }
      /**
       * 判断是否为普通周末
       *
       * @param date - 日期
       * @returns 是否为周六或周日
       */
      isWeekend(date) {
        const day = date.getDay();
        return day === 0 || day === 6;
      }
      /**
       * 获取日期的综合类型
       *
       * 优先级：法定假日 > 调休 > 周末 > 普通
       *
       * @param date - 日期
       * @returns 对应的 HolidayType 枚举值
       */
      getDateType(date) {
        const info = this.getHolidayInfo(date);
        if (info)
          return info.type;
        if (this.isWeekend(date))
          return "weekend" /* WEEKEND */;
        return "normal" /* NORMAL */;
      }
      /**
       * 获取日期的显示名称
       *
       * 如 "春节"、"国庆节"、"班"、"" 等
       *
       * @param date - 日期
       * @returns 名称字符串，无则 undefined
       */
      getDateName(date) {
        const info = this.getHolidayInfo(date);
        return info == null ? void 0 : info.name;
      }
      /**
       * 获取日期角标（用于在格子中显示"休"/"班"标签）
       *
       * @param date - 日期
       * @returns 角标文本和类型，无需显示返回 undefined
       */
      getDateBadge(date) {
        const info = this.getHolidayInfo(date);
        if (!info)
          return void 0;
        if (info.type === "legal" /* LEGAL */ && info.isOff) {
          return { text: "\u4F11", type: "off" };
        }
        if (info.type === "workday" /* WORKDAY */) {
          return { text: "\u73ED", type: "work" };
        }
        return void 0;
      }
      // ── 月度查询 ─────────────────────────────
      /**
       * 获取指定月份的所有节假日
       *
       * @param year  - 年份
       * @param month - 月份 (1-based)
       * @returns 该月的节假日记录
       */
      getMonthHolidays(year, month) {
        const holidays = this.getYearHolidays(year);
        return holidays.filter((h) => {
          const date = new Date(h.date);
          return date.getMonth() + 1 === month;
        });
      }
      // ── 数据更新（预留）──────────────────────
      /**
       * 从网络更新节假日数据（预留接口）
       *
       * TODO: 接入 timor.tech 或类似 API 实现自动更新
       *
       * @param year - 需要更新的年份
       * @returns 是否成功
       */
      async updateFromNetwork(year) {
        console.log(`\u8282\u5047\u65E5\u6570\u636E\uFF1A\u4F7F\u7528\u5185\u7F6E\u6570\u636E ${year}\u5E74`);
        return true;
      }
      // ── 私有工具 ─────────────────────────────
      /**
       * 格式化日期为 YYYY-MM-DD
       */
      formatDate(date) {
        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, "0");
        const day = String(date.getDate()).padStart(2, "0");
        return `${year}-${month}-${day}`;
      }
    };
    holidayManager = new HolidayManager();
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MonthlyTasksPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/TaskParser.ts
var import_obsidian = require("obsidian");

// src/TaskModel.ts
function generateTaskId(filePath, lineNumber) {
  return `${filePath}:${lineNumber}`;
}
function parsePriority(content) {
  if (content.includes("\u23EB") || content.includes("\u{1F534}"))
    return 3 /* HIGH */;
  if (content.includes("\u{1F53C}") || content.includes("\u{1F7E1}"))
    return 2 /* MEDIUM */;
  return 0 /* NONE */;
}
function cleanTaskContent(rawLine) {
  return rawLine.replace(/^\s*- \[[ x]\]\s*/i, "").replace(/📅\s*\d{4}-\d{2}-\d{2}/g, "").replace(/⏳\s*\d{4}-\d{2}-\d{2}/g, "").replace(/🛫\s*\d{4}-\d{2}-\d{2}/g, "").replace(/⏰\s*\d{2}:\d{2}/g, "").replace(/⏫|🔼/g, "").replace(/🔴|🟡/g, "").trim();
}
function extractDueDate(rawLine) {
  const match = rawLine.match(/📅\s*(\d{4}-\d{2}-\d{2})/);
  return match == null ? void 0 : match[1];
}
function extractStartDate(rawLine) {
  const match = rawLine.match(/🛫\s*(\d{4}-\d{2}-\d{2})/);
  return match == null ? void 0 : match[1];
}
function isTaskLine(line) {
  return /^\s*- \[[ x]\]\s*/i.test(line);
}
function isTaskCompleted(line) {
  return /^\s*- \[x\]\s*/i.test(line);
}
function groupTasksByDate(tasks) {
  const map = /* @__PURE__ */ new Map();
  for (const task of tasks) {
    if (!task.dueDate)
      continue;
    const displayDate = task.startDate || task.dueDate;
    const existing = map.get(displayDate) || [];
    existing.push(task);
    map.set(displayDate, existing);
  }
  for (const [date, dateTasks] of map) {
    dateTasks.sort((a, b) => {
      if (a.completed !== b.completed)
        return a.completed ? 1 : -1;
      return b.priority - a.priority;
    });
    map.set(date, dateTasks);
  }
  return map;
}
function isMultiDayTask(task) {
  return !!task.startDate && task.startDate !== task.dueDate;
}
function getMultiDayDuration(task) {
  if (!isMultiDayTask(task))
    return 1;
  const start = new Date(task.startDate);
  const end = new Date(task.dueDate);
  return Math.ceil((end.getTime() - start.getTime()) / (1e3 * 60 * 60 * 24)) + 1;
}
function getMultiDayTaskRangeInMonth(task, year, month, firstDayOfWeek = 0) {
  if (!isMultiDayTask(task) || !task.startDate)
    return null;
  const taskStart = new Date(task.startDate);
  const taskEnd = new Date(task.dueDate);
  const monthStart = new Date(year, month, 1);
  const monthEnd = new Date(year, month + 1, 0);
  if (taskEnd < monthStart || taskStart > monthEnd)
    return null;
  const firstDayIndex = monthStart.getDay();
  const paddingDays = (firstDayIndex - firstDayOfWeek + 7) % 7;
  const effectiveStart = taskStart < monthStart ? monthStart : taskStart;
  const effectiveEnd = taskEnd > monthEnd ? monthEnd : taskEnd;
  const startDayOfMonth = effectiveStart.getDate() - 1;
  const endDayOfMonth = effectiveEnd.getDate() - 1;
  return { startIndex: paddingDays + startDayOfMonth, endIndex: paddingDays + endDayOfMonth };
}
function getTaskWeekSpans(task, year, month, firstDayOfWeek = 0) {
  if (!isMultiDayTask(task) || !task.startDate)
    return [];
  const range = getMultiDayTaskRangeInMonth(task, year, month, firstDayOfWeek);
  if (!range)
    return [];
  const { startIndex, endIndex } = range;
  const spans = [];
  let currentIndex = startIndex;
  while (currentIndex <= endIndex) {
    const weekIndex = Math.floor(currentIndex / 7);
    const weekStart = weekIndex * 7;
    const weekEnd = weekStart + 6;
    spans.push({
      weekIndex,
      startCol: Math.max(currentIndex, weekStart) - weekStart,
      endCol: Math.min(endIndex, weekEnd) - weekStart
    });
    currentIndex = weekEnd + 1;
  }
  return spans;
}
function isOverdue(dateStr) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const checkDate = new Date(dateStr);
  checkDate.setHours(0, 0, 0, 0);
  return checkDate < today;
}

// src/TaskParser.ts
var TaskParser = class {
  constructor(app) {
    /** 最近一次的解析结果缓存（5秒内有效） */
    this.cache = null;
    /** 上次缓存的更新时间戳 */
    this.lastParseTime = 0;
    /** 缓存有效期（毫秒），防止高频调用时反复扫描整个 Vault */
    this.CACHE_DURATION = 5e3;
    this.app = app;
  }
  // ── 任务扫描 ──────────────────────────────
  /**
   * 解析 Vault 中的所有任务
   *
   * 遍历仓库中所有 Markdown 文件，提取任务行并构建索引。
   * 结果会缓存 5 秒，在此期间的重复调用直接返回缓存。
   *
   * @param forceRefresh - 是否强制忽略缓存重新扫描
   * @returns 解析结果（包含任务列表和按日期分组的 Map）
   */
  async parseAllTasks(forceRefresh = false) {
    if (!forceRefresh && this.cache && Date.now() - this.lastParseTime < this.CACHE_DURATION) {
      return this.cache;
    }
    const tasks = [];
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      const fileTasks = await this.parseFile(file);
      tasks.push(...fileTasks);
    }
    const taskMap = groupTasksByDate(tasks);
    const now = Date.now();
    this.cache = { tasks, taskMap, parseTime: now };
    this.lastParseTime = now;
    return this.cache;
  }
  /**
   * 解析单个文件中的任务
   *
   * 利用 Obsidian 的 `MetadataCache` 获取文件的结构化信息，
   * 只检查被识别为 `task` 的 list item，避免逐行遍历。
   *
   * @param file - 目标 Markdown 文件
   * @returns 该文件中找到的任务列表
   */
  async parseFile(file) {
    const tasks = [];
    const cache = this.app.metadataCache.getFileCache(file);
    if (!(cache == null ? void 0 : cache.listItems))
      return tasks;
    const content = await this.app.vault.cachedRead(file);
    const lines = content.split("\n");
    for (const item of cache.listItems) {
      if (item.task === void 0)
        continue;
      const lineNumber = item.position.start.line;
      const line = lines[lineNumber];
      if (!line || !isTaskLine(line))
        continue;
      const task = this.parseTaskLine(line, file.path, lineNumber);
      if (task)
        tasks.push(task);
    }
    return tasks;
  }
  /**
   * 解析单行文本为 Task 对象
   *
   * 从原始行中提取：内容、优先级、日期、完成状态等信息。
   *
   * @param line       - 原始行文本
   * @param filePath   - 文件路径
   * @param lineNumber - 行号
   * @returns 解析后的 Task 对象，如果内容为空则返回 null
   */
  parseTaskLine(line, filePath, lineNumber) {
    const content = cleanTaskContent(line);
    if (!content)
      return null;
    return {
      id: generateTaskId(filePath, lineNumber),
      content,
      rawLine: line,
      filePath,
      lineNumber,
      completed: isTaskCompleted(line),
      startDate: extractStartDate(line),
      dueDate: extractDueDate(line),
      priority: parsePriority(line),
      createdAt: Date.now()
    };
  }
  // ── 查询方法 ──────────────────────────────
  /**
   * 获取指定日期的所有任务
   *
   * @param dateStr        - 日期字符串 (YYYY-MM-DD)
   * @param forceRefresh   - 是否强制刷新缓存
   * @returns 该日期的任务列表
   */
  async getTasksByDate(dateStr, forceRefresh = false) {
    const result = await this.parseAllTasks(forceRefresh);
    return result.taskMap.get(dateStr) || [];
  }
  /**
   * 获取指定日期范围内的任务
   *
   * @param startDate - 起始日期 (YYYY-MM-DD)
   * @param endDate   - 结束日期 (YYYY-MM-DD)
   * @returns 按日期索引的任务子集
   */
  async getTasksByDateRange(startDate, endDate) {
    const result = await this.parseAllTasks();
    const filteredMap = /* @__PURE__ */ new Map();
    for (const [dateStr, tasks] of result.taskMap) {
      if (dateStr >= startDate && dateStr <= endDate) {
        filteredMap.set(dateStr, tasks);
      }
    }
    return filteredMap;
  }
  // ── 写入方法 ──────────────────────────────
  /**
   * 切换任务完成状态
   *
   * 直接修改文件中的复选框状态：
   * `- [ ]` → `- [x]` 或反之。
   *
   * @param task - 要切换的任务对象
   * @returns 操作是否成功
   */
  async toggleTask(task) {
    try {
      const file = this.app.vault.getAbstractFileByPath(task.filePath);
      if (!(file instanceof import_obsidian.TFile))
        return false;
      const content = await this.app.vault.read(file);
      const lines = content.split("\n");
      if (task.lineNumber >= lines.length)
        return false;
      const line = lines[task.lineNumber];
      lines[task.lineNumber] = isTaskCompleted(line) ? line.replace(/- \[[xX]\]/, "- [ ]") : line.replace(/- \[ \]/, "- [x]");
      await this.app.vault.modify(file, lines.join("\n"));
      this.invalidateCache();
      return true;
    } catch (error) {
      console.error("\u5207\u6362\u4EFB\u52A1\u72B6\u6001\u5931\u8D25:", error);
      return false;
    }
  }
  /**
   * 向指定文件写入一条新任务
   *
   * 任务格式遵循 Dataview/Tasks 插件标准：
   * ```
   * - [ ] [优先级] 内容 📅 截止日期 🛫 开始日期 ⏰ 时间
   * ```
   *
   * @param filePath   - 目标文件路径
   * @param content    - 任务描述文本
   * @param dueDate    - 截止日期 (YYYY-MM-DD)
   * @param isAllDay    - 是否为全天任务（影响是否添加时间标记）
   * @param time       - 具体时间 (HH:mm)，仅非全天任务时使用
   * @param priority   - 优先级 (0=普通, 2=中, 3=高)
   * @param startDate  - 开始日期，用于跨天任务
   * @returns 操作是否成功
   */
  async createTask(filePath, content, dueDate, isAllDay, time, priority, startDate) {
    try {
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (!(file instanceof import_obsidian.TFile))
        return false;
      const fileContent = await this.app.vault.read(file);
      const priorityMark = priority === 3 ? "\u23EB " : priority === 2 ? "\u{1F53C} " : "";
      let taskLine = `- [ ] ${priorityMark}${content}`;
      if (!isAllDay && time)
        taskLine += ` \u23F0 ${time}`;
      if (startDate && startDate !== dueDate)
        taskLine += ` \u{1F6EB} ${startDate}`;
      if (dueDate)
        taskLine += ` \u{1F4C5} ${dueDate}`;
      await this.app.vault.modify(file, fileContent + "\n" + taskLine + "\n");
      this.invalidateCache();
      return true;
    } catch (error) {
      console.error("\u521B\u5EFA\u4EFB\u52A1\u5931\u8D25:", error);
      return false;
    }
  }
  /**
   * 为指定日期创建任务（智能选择存储位置）
   *
   * 存储优先级：
   * 1. 如果当天存在日记文件 → 写入日记文件
   * 2. 否则 → 创建或追加到 `任务/YYYYMM任务.md`
   *
   * @param date     - 目标日期
   * @param content  - 任务内容
   * @param isAllDay - 是否全天任务
   * @param time    - 具体时间
   * @param priority - 优先级
   * @param endDate  - 结束日期（跨天任务用）
   * @returns 是否创建成功
   */
  async createTaskForDate(date, content, isAllDay = true, time, priority, endDate) {
    const dateStr = this.formatDate(date);
    const endDateStr = endDate ? this.formatDate(endDate) : dateStr;
    const dailyNotePath = this.findDailyNotePath(date);
    if (dailyNotePath) {
      return this.createTask(dailyNotePath, content, endDateStr, isAllDay, time, priority, dateStr);
    }
    const defaultFile = await this.getOrCreateDefaultTaskFile(date);
    return defaultFile ? this.createTask(defaultFile, content, endDateStr, isAllDay, time, priority, dateStr) : false;
  }
  // ── 文件查找与创建 ────────────────────────
  /**
   * 尝试查找当天的日记文件
   *
   * 检查多种常见的日记文件路径格式：
   * - YYYY-MM-DD.md（Obsidian 默认）
   * - YYYY/MM/DD.md
   * - 日记/YYYY-MM-DD.md
   * - Daily/YYYY-MM-DD.md
   *
   * @param date - 目标日期
   * @returns 找到的文件路径，未找到返回 null
   */
  findDailyNotePath(date) {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, "0");
    const d = String(date.getDate()).padStart(2, "0");
    const formats = [
      `${y}-${m}-${d}.md`,
      `${y}/${m}/${d}.md`,
      `\u65E5\u8BB0/${y}-${m}-${d}.md`,
      `Daily/${y}-${m}-${d}.md`
    ];
    for (const format of formats) {
      const file = this.app.vault.getAbstractFileByPath(format);
      if (file instanceof import_obsidian.TFile)
        return format;
    }
    return null;
  }
  /**
   * 获取或创建默认任务存储文件
   *
   * 文件路径格式：`任务/YYYYMM任务.md`
   * 如果文件不存在则自动创建并写入头部说明。
   *
   * @param date - 用于确定年月的日期
   * @returns 文件路径，创建失败返回 null
   */
  async getOrCreateDefaultTaskFile(date) {
    const now = date || new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, "0");
    const folderPath = "\u4EFB\u52A1";
    const filePath = `${folderPath}/${year}${month}\u4EFB\u52A1.md`;
    if (this.app.vault.getAbstractFileByPath(filePath) instanceof import_obsidian.TFile)
      return filePath;
    try {
      await this.ensureFolderExists(folderPath);
      await this.app.vault.create(filePath, `# ${year}\u5E74${month}\u6708\u4EFB\u52A1\u5217\u8868

> \u8FD9\u662F\u7531\u300C\u6708\u5386\u4EFB\u52A1\u300D\u63D2\u4EF6\u81EA\u52A8\u521B\u5EFA\u7684\u4EFB\u52A1\u6587\u4EF6\u3002
> \u5728\u6708\u5386\u89C6\u56FE\u4E2D\u6DFB\u52A0\u7684\u4EFB\u52A1\u4F1A\u4FDD\u5B58\u5728\u8FD9\u91CC\u3002

`);
      return filePath;
    } catch (error) {
      console.error("\u521B\u5EFA\u9ED8\u8BA4\u4EFB\u52A1\u6587\u4EF6\u5931\u8D25:", error);
      return null;
    }
  }
  /**
   * 确保文件夹及其父目录存在
   *
  * 递归检查并创建路径中的每一级目录。
   *
   * @param folderPath - 文件夹路径（如 "任务/2026"）
   */
  async ensureFolderExists(folderPath) {
    const parts = folderPath.split("/");
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(currentPath)) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
  // ── 缓存与工具 ────────────────────────────
  /**
   * 使缓存失效
   *
   * 在文件被修改后调用，确保下次查询会重新扫描。
   */
  invalidateCache() {
    this.cache = null;
    this.lastParseTime = 0;
  }
  /**
   * 格式化日期为 YYYY-MM-DD 字符串
   *
   * @param date - 日期对象
   * @returns ISO 格式日期字符串
   */
  formatDate(date) {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
  }
  // ── 辅助查询 ────────────────────────────
  /**
   * 获取所有有任务的日期列表
   *
   * @returns 日期字符串数组
   */
  async getDatesWithTasks() {
    const result = await this.parseAllTasks();
    return Array.from(result.taskMap.keys());
  }
  /**
   * 搜索包含关键词的任务
   *
   * 不区分大小写的模糊搜索。
   *
   * @param keyword - 搜索关键词
   * @returns 匹配的任务列表
   */
  async searchTasks(keyword) {
    const result = await this.parseAllTasks();
    return result.tasks.filter((task) => task.content.toLowerCase().includes(keyword.toLowerCase()));
  }
  /**
   * 获取任务统计摘要
   *
   * @returns 总数、已完成数、待完成数、逾期数
   */
  async getTaskStats() {
    const result = await this.parseAllTasks();
    const today = new Date().toISOString().split("T")[0];
    let completed = 0, pending = 0, overdue = 0;
    for (const task of result.tasks) {
      if (task.completed)
        completed++;
      else {
        pending++;
        if (task.dueDate && task.dueDate < today)
          overdue++;
      }
    }
    return { total: result.tasks.length, completed, pending, overdue };
  }
};

// src/MonthlyView.ts
var import_obsidian2 = require("obsidian");

// src/Calendar.ts
var WEEKDAY_NAMES = ["\u65E5", "\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D"];
var MONTH_NAMES = ["1\u6708", "2\u6708", "3\u6708", "4\u6708", "5\u6708", "6\u6708", "7\u6708", "8\u6708", "9\u6708", "10\u6708", "11\u6708", "12\u6708"];
function getDaysInMonth(year, month) {
  return new Date(year, month + 1, 0).getDate();
}
function getFirstDayOfMonth(year, month) {
  return new Date(year, month, 1).getDay();
}
function isToday(date) {
  const today = new Date();
  return date.getFullYear() === today.getFullYear() && date.getMonth() === today.getMonth() && date.getDate() === today.getDate();
}
function isWeekend(date) {
  const day = date.getDay();
  return day === 0 || day === 6;
}
function formatDate(date) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}
function generateMonthCalendar(year, month, firstDayOfWeek = 1) {
  const days = [];
  const daysInMonth = getDaysInMonth(year, month);
  const firstDayWeekday = getFirstDayOfMonth(year, month);
  let daysFromPrevMonth = firstDayWeekday - firstDayOfWeek;
  if (daysFromPrevMonth < 0)
    daysFromPrevMonth += 7;
  const prevMonth = month === 0 ? 11 : month - 1;
  const prevYear = month === 0 ? year - 1 : year;
  const daysInPrevMonth = getDaysInMonth(prevYear, prevMonth);
  for (let i = daysFromPrevMonth - 1; i >= 0; i--) {
    const day = daysInPrevMonth - i;
    const date = new Date(prevYear, prevMonth, day);
    days.push({
      date,
      day,
      month: prevMonth,
      year: prevYear,
      isCurrentMonth: false,
      isToday: isToday(date),
      isWeekend: isWeekend(date),
      dayOfWeek: date.getDay()
    });
  }
  for (let day = 1; day <= daysInMonth; day++) {
    const date = new Date(year, month, day);
    days.push({
      date,
      day,
      month,
      year,
      isCurrentMonth: true,
      isToday: isToday(date),
      isWeekend: isWeekend(date),
      dayOfWeek: date.getDay()
    });
  }
  const remainingDays = 42 - days.length;
  const nextMonth = month === 11 ? 0 : month + 1;
  const nextYear = month === 11 ? year + 1 : year;
  for (let day = 1; day <= remainingDays; day++) {
    const date = new Date(nextYear, nextMonth, day);
    days.push({
      date,
      day,
      month: nextMonth,
      year: nextYear,
      isCurrentMonth: false,
      isToday: isToday(date),
      isWeekend: isWeekend(date),
      dayOfWeek: date.getDay()
    });
  }
  return { year, month, days, weekCount: days.length / 7 };
}
function getPrevMonth(year, month) {
  return month === 0 ? { year: year - 1, month: 11 } : { year, month: month - 1 };
}
function getNextMonth(year, month) {
  return month === 11 ? { year: year + 1, month: 0 } : { year, month: month + 1 };
}
function getCurrentYearMonth() {
  const now = new Date();
  return { year: now.getFullYear(), month: now.getMonth() };
}
function getMonthTitle(year, month) {
  return `${year}\u5E74 ${MONTH_NAMES[month]}`;
}

// src/LunarCalendar.ts
var LUNAR_MONTH_NAMES = [
  "\u6B63",
  "\u4E8C",
  "\u4E09",
  "\u56DB",
  "\u4E94",
  "\u516D",
  "\u4E03",
  "\u516B",
  "\u4E5D",
  "\u5341",
  "\u51AC",
  "\u814A"
];
var LUNAR_DAY_NAMES = [
  "\u521D\u4E00",
  "\u521D\u4E8C",
  "\u521D\u4E09",
  "\u521D\u56DB",
  "\u521D\u4E94",
  "\u521D\u516D",
  "\u521D\u4E03",
  "\u521D\u516B",
  "\u521D\u4E5D",
  "\u521D\u5341",
  "\u5341\u4E00",
  "\u5341\u4E8C",
  "\u5341\u4E09",
  "\u5341\u56DB",
  "\u5341\u4E94",
  "\u5341\u516D",
  "\u5341\u4E03",
  "\u5341\u516B",
  "\u5341\u4E5D",
  "\u4E8C\u5341",
  "\u5EFF\u4E00",
  "\u5EFF\u4E8C",
  "\u5EFF\u4E09",
  "\u5EFF\u56DB",
  "\u5EFF\u4E94",
  "\u5EFF\u516D",
  "\u5EFF\u4E03",
  "\u5EFF\u516B",
  "\u5EFF\u4E5D",
  "\u4E09\u5341"
];
var TIAN_GAN = ["\u7532", "\u4E59", "\u4E19", "\u4E01", "\u620A", "\u5DF1", "\u5E9A", "\u8F9B", "\u58EC", "\u7678"];
var DI_ZHI = ["\u5B50", "\u4E11", "\u5BC5", "\u536F", "\u8FB0", "\u5DF3", "\u5348", "\u672A", "\u7533", "\u9149", "\u620C", "\u4EA5"];
var ZODIAC_ANIMALS = ["\u9F20", "\u725B", "\u864E", "\u5154", "\u9F99", "\u86C7", "\u9A6C", "\u7F8A", "\u7334", "\u9E21", "\u72D7", "\u732A"];
var TRADITIONAL_HOLIDAYS = {
  "1-1": "\u6625\u8282",
  "1-15": "\u5143\u5BB5",
  "2-2": "\u9F99\u62AC\u5934",
  "5-5": "\u7AEF\u5348",
  "7-7": "\u4E03\u5915",
  "7-15": "\u4E2D\u5143",
  "8-15": "\u4E2D\u79CB",
  "9-9": "\u91CD\u9633",
  "10-1": "\u5BD2\u8863",
  "10-15": "\u4E0B\u5143",
  "12-8": "\u814A\u516B",
  "12-23": "\u5C0F\u5E74",
  "12-30": "\u9664\u5915"
};
var LUNAR_INFO = [
  19416,
  19168,
  42352,
  21717,
  53856,
  55632,
  91476,
  22176,
  39632,
  21970,
  19168,
  42422,
  42192,
  53840,
  119381,
  46400,
  54944,
  44450,
  38320,
  84343,
  18800,
  42160,
  46261,
  27216,
  27968,
  109396,
  11104,
  38256,
  21234,
  18800,
  25958,
  54432,
  59984,
  28309,
  23248,
  11104,
  100067,
  37600,
  116951,
  51536,
  54432,
  120998,
  46416,
  22176,
  107956,
  9680,
  37584,
  53938,
  43344,
  46423,
  27808,
  46416,
  86869,
  19872,
  42448,
  83315,
  21200,
  43432,
  59728,
  27296,
  44710,
  43856,
  19296,
  43748,
  42352,
  21088,
  62051,
  55632,
  23383,
  22176,
  38608,
  19925,
  19152,
  42192,
  54484,
  53840,
  54616,
  46400,
  46496,
  103846,
  38320,
  18864,
  43380,
  42160,
  45690,
  27216,
  27968,
  44870,
  43872,
  38256,
  19189,
  18800,
  25776,
  29859,
  59984,
  27480,
  21952,
  43872,
  38613,
  37600,
  51552,
  55636,
  54432,
  55888,
  30034,
  22176,
  43959,
  9680,
  37584,
  51893,
  43344,
  46240,
  47780,
  44368,
  21977,
  19360,
  42416,
  86390,
  21168,
  43312,
  31060,
  27296,
  44368,
  23378,
  19296,
  42726,
  42208,
  53856,
  60005,
  54576,
  23200,
  30371,
  38608,
  19415,
  19152,
  42192,
  118966,
  53840,
  54560,
  56645,
  46496,
  22224,
  21938,
  18864,
  42359,
  42160,
  43600,
  111189,
  27936,
  44448,
  84835,
  37744,
  18936,
  18800,
  25776,
  92326,
  59984,
  27424,
  108228,
  43744,
  41696,
  53987,
  51552,
  54615,
  54432,
  55888,
  23893,
  22176,
  42704,
  21972,
  21200,
  43448,
  43344,
  46240,
  46758,
  44368,
  21920,
  43940,
  42416,
  21168,
  45683,
  26928,
  29495,
  27296,
  44368,
  84821,
  19296,
  42352,
  21732,
  53600,
  59752,
  54560,
  55968,
  92838,
  22224,
  19168,
  43476,
  41680,
  53584,
  62034,
  54560
];
function getLunarYearDays(year) {
  let sum = 348;
  const info = LUNAR_INFO[year - 1900];
  for (let i = 32768; i > 8; i >>= 1) {
    sum += info & i ? 1 : 0;
  }
  return sum + getLeapDays(year);
}
function getLeapDays(year) {
  if (getLeapMonth(year)) {
    return LUNAR_INFO[year - 1900] & 65536 ? 30 : 29;
  }
  return 0;
}
function getLeapMonth(year) {
  return LUNAR_INFO[year - 1900] & 15;
}
function getLunarMonthDays(year, month) {
  return LUNAR_INFO[year - 1900] & 65536 >> month ? 30 : 29;
}
function solarToLunar(date) {
  let year = date.getFullYear();
  let month = date.getMonth() + 1;
  let day = date.getDate();
  if (year < 1900 || year > 2100) {
    throw new Error("\u5E74\u4EFD\u8D85\u51FA\u652F\u6301\u8303\u56F4\uFF081900-2100\uFF09");
  }
  let offset = Math.floor((date.getTime() - new Date(1900, 0, 31).getTime()) / 864e5);
  let lunarYear = 1900;
  let daysInYear = getLunarYearDays(lunarYear);
  while (offset >= daysInYear) {
    offset -= daysInYear;
    lunarYear++;
    daysInYear = getLunarYearDays(lunarYear);
  }
  const leapMonth = getLeapMonth(lunarYear);
  let isLeap = false;
  let lunarMonth = 1;
  while (true) {
    let daysInMonth = getLunarMonthDays(lunarYear, lunarMonth);
    if (leapMonth === lunarMonth && !isLeap) {
      if (offset >= daysInMonth) {
        offset -= daysInMonth;
        lunarMonth++;
      } else {
        isLeap = true;
        break;
      }
    } else {
      if (offset >= daysInMonth) {
        offset -= daysInMonth;
        lunarMonth++;
      } else {
        break;
      }
    }
  }
  const lunarDay = offset + 1;
  const ganIndex = (lunarYear - 4) % 10;
  const zhiIndex = (lunarYear - 4) % 12;
  const ganZhiYear = TIAN_GAN[ganIndex] + DI_ZHI[zhiIndex];
  const zodiac = ZODIAC_ANIMALS[zhiIndex];
  return { year: lunarYear, month: lunarMonth, day: lunarDay, isLeap, ganZhiYear, zodiac };
}
function getLunarDayText(lunarDate) {
  if (lunarDate.day === 1) {
    const monthName = LUNAR_MONTH_NAMES[lunarDate.month - 1];
    return lunarDate.isLeap ? `\u95F0${monthName}\u6708` : `${monthName}\u6708`;
  }
  return LUNAR_DAY_NAMES[lunarDate.day - 1];
}
function getTraditionalHoliday(lunarDate) {
  const key = `${lunarDate.month}-${lunarDate.day}`;
  return TRADITIONAL_HOLIDAYS[key];
}
function getLunarInfo(date) {
  try {
    const lunarDate = solarToLunar(date);
    const holiday = getTraditionalHoliday(lunarDate);
    if (holiday) {
      return { text: holiday, isFestival: true, festivalName: holiday };
    }
    return { text: getLunarDayText(lunarDate), isFestival: false };
  } catch (e) {
    return { text: "", isFestival: false };
  }
}
function isSpecialLunarDay(date) {
  try {
    const lunarDate = solarToLunar(date);
    return lunarDate.day === 1 || lunarDate.day === 15;
  } catch (e) {
    return false;
  }
}

// src/MonthlyView.ts
init_HolidayManager();
var VIEW_TYPE_MONTHLY = "monthly-tasks-view";
var MonthlyView = class extends import_obsidian2.ItemView {
  /**
   * 构造函数
   *
   * @param leaf      - Obsidian 工作区叶子节点
   * @param taskParser - 任务解析器实例
   * @param plugin    - 插件实例（读取设置）
   */
  constructor(leaf, taskParser, plugin) {
    super(leaf);
    this.taskParser = taskParser;
    this.plugin = plugin;
    const { year, month } = getCurrentYearMonth();
    this.currentYear = year;
    this.currentMonth = month;
  }
  /** 返回视图类型标识 */
  getViewType() {
    return VIEW_TYPE_MONTHLY;
  }
  /** 返回视图在标题栏中显示的文字 */
  getDisplayText() {
    return "\u6708\u5386\u4EFB\u52A1";
  }
  /** 返回图标名称（使用 Obsidian 内置的 calendar 图标） */
  getIcon() {
    return "calendar";
  }
  /**
   * 视图被打开时调用（Obsidian 自动触发）
   *
   * 创建容器元素并执行首次渲染。
   */
  async onOpen() {
    this.containerEl = this.contentEl.createDiv("monthly-tasks-container");
    await this.render();
  }
  /**
   * 视图关闭时调用
   *
   * 清理 DOM 以防止内存泄漏。
   */
  async onClose() {
    this.containerEl.empty();
  }
  /**
   * 渲染整个视图
   *
   * 首次打开时创建完整 DOM 结构，
   * 后续刷新时只更新数据不重建结构（提升性能）。
   */
  async render() {
    if (this.containerEl.childElementCount === 0) {
      this.renderHeader();
      this.renderWeekdayHeader();
      this.gridEl = this.containerEl.createDiv("calendar-grid");
    }
    await this.renderCalendarGrid();
  }
  // ── 渲染子区域 ─────────────────────────
  /**
   * 渲染头部导航栏
   *
   * 包含：上/下月按钮、月份标题（可点击跳转）、今天按钮、关闭按钮
   */
  renderHeader() {
    this.headerEl = this.containerEl.createDiv("monthly-header");
    const leftGroup = this.headerEl.createDiv("header-btn-group");
    const prevBtn = leftGroup.createDiv("nav-btn prev-btn");
    prevBtn.innerHTML = '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6"></polyline></svg>';
    prevBtn.addEventListener("click", () => this.navigateMonth(-1));
    const titleEl = this.headerEl.createDiv("month-title clickable");
    titleEl.textContent = getMonthTitle(this.currentYear, this.currentMonth);
    titleEl.addEventListener("click", () => this.openDatePicker());
    const rightGroup = this.headerEl.createDiv("header-btn-group");
    const nextBtn = rightGroup.createDiv("nav-btn next-btn");
    nextBtn.innerHTML = '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6"></polyline></svg>';
    nextBtn.addEventListener("click", () => this.navigateMonth(1));
    const todayBtn = rightGroup.createDiv("today-btn");
    todayBtn.textContent = "\u56DE\u5230\u672C\u6708\u663E\u793A";
    todayBtn.addEventListener("click", () => this.goToToday());
    const closeBtn = rightGroup.createDiv("nav-btn close-btn");
    closeBtn.innerHTML = '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>';
    closeBtn.addEventListener("click", () => this.closeView());
  }
  /**
   * 关闭当前视图（从工作区移除）
   */
  closeView() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_MONTHLY).forEach((leaf) => leaf.detach());
  }
  /**
   * 打开日期选择器弹窗
   *
   * 用户点击月份标题后弹出，可选择任意年/月跳转。
   * 跳转后只更新网格数据，不重建整个视图。
   */
  openDatePicker() {
    const modal = new DatePickerModal(this.app, this.currentYear, this.currentMonth, async (year, month) => {
      this.currentYear = year;
      this.currentMonth = month;
      await this.renderCalendarGrid();
    });
    modal.open();
  }
  /**
   * 刷新视图
   *
   * @param force - true=完全重建（包括头部），false=仅更新网格数据
   */
  async refresh(force = false) {
    this.taskParser.invalidateCache();
    if (force) {
      await this.render();
    } else {
      await this.renderCalendarGrid();
    }
  }
  /**
   * 渲染星期标题行（日 一 二 ... 六）
   *
   * 根据设置中的 firstDayOfWeek 决定排列顺序。
   */
  renderWeekdayHeader() {
    const weekdayEl = this.containerEl.createDiv("weekday-header");
    const firstDayOfWeek = this.plugin.settings.firstDayOfWeek;
    for (let i = 0; i < 7; i++) {
      const dayIndex = (firstDayOfWeek + i) % 7;
      const dayEl = weekdayEl.createDiv(`weekday-cell${dayIndex === 0 || dayIndex === 6 ? " weekend" : ""}`);
      dayEl.textContent = WEEKDAY_NAMES[dayIndex];
    }
  }
  /**
   * 渲染日历网格的核心方法
   *
   * 执行流程：
   * 1. 更新标题文字
   * 2. 解析所有任务并按日期分组
   * 3. 分离单日任务和跨天任务
   * 4. 渲染每个日期格子
   * 5. 在顶层渲染跨天任务条
   */
  async renderCalendarGrid() {
    const titleEl = this.headerEl.querySelector(".month-title");
    if (titleEl)
      titleEl.textContent = getMonthTitle(this.currentYear, this.currentMonth);
    this.gridEl.empty();
    const calendar = generateMonthCalendar(this.currentYear, this.currentMonth, this.plugin.settings.firstDayOfWeek);
    const taskMap = await this.taskParser.parseAllTasks(true);
    const singleDayTasks = /* @__PURE__ */ new Map();
    const multiDayTasks = [];
    for (const [dateStr, tasks] of taskMap.taskMap) {
      const singleTasks = [];
      for (const task of tasks) {
        if (isMultiDayTask(task))
          multiDayTasks.push(task);
        else
          singleTasks.push(task);
      }
      if (singleTasks.length > 0)
        singleDayTasks.set(dateStr, singleTasks);
    }
    for (const day of calendar.days) {
      this.renderDayCell(day, singleDayTasks.get(formatDate(day.date)) || []);
    }
    this.renderMultiDayTaskBars(multiDayTasks, calendar.days);
  }
  /**
   * 渲染跨天任务横条
   *
   * 跨天任务不是放在单个格子里，而是以横条形式
   * 浮在整个日历网格上方，横跨多个日期列。
   *
   * 算法要点：
   * 1. 将每个跨天任务按周拆分为多个片段
   * 2. 每周的片段独立计算垂直位置（避免重叠）
   * 3. 使用绝对定位（百分比坐标）放置到正确位置
   */
  renderMultiDayTaskBars(multiDayTasks, calendarDays) {
    if (multiDayTasks.length === 0)
      return;
    const taskSpans = [];
    for (const task of multiDayTasks) {
      const spans = getTaskWeekSpans(task, this.currentYear, this.currentMonth, this.plugin.settings.firstDayOfWeek);
      for (const span of spans) {
        taskSpans.push({ task, weekIndex: span.weekIndex, startCol: span.startCol, endCol: span.endCol });
      }
    }
    const weekGroups = /* @__PURE__ */ new Map();
    for (const span of taskSpans) {
      const existing = weekGroups.get(span.weekIndex) || [];
      existing.push(span);
      weekGroups.set(span.weekIndex, existing);
    }
    const weekRows = /* @__PURE__ */ new Map();
    for (const [weekIndex, spans] of weekGroups) {
      spans.sort((a, b) => a.startCol - b.startCol);
      const taskRows = /* @__PURE__ */ new Map();
      const occupiedRows = [];
      for (const span of spans) {
        let rowIndex = 0;
        while (true) {
          if (!occupiedRows[rowIndex])
            occupiedRows[rowIndex] = [];
          const hasConflict = occupiedRows[rowIndex].some((occ) => !(span.endCol < occ.start || span.startCol > occ.end));
          if (!hasConflict) {
            taskRows.set(span.task.id, rowIndex);
            occupiedRows[rowIndex].push({ start: span.startCol, end: span.endCol });
            break;
          }
          rowIndex++;
        }
      }
      weekRows.set(weekIndex, taskRows);
    }
    const multiDayContainer = this.gridEl.createDiv("multiday-task-container");
    for (const span of taskSpans) {
      const weekTaskRows = weekRows.get(span.weekIndex);
      if (!weekTaskRows)
        continue;
      const rowIndex = weekTaskRows.get(span.task.id);
      if (rowIndex === void 0)
        continue;
      const barEl = multiDayContainer.createDiv("multiday-task-bar");
      barEl.textContent = span.task.content;
      barEl.addClass(`multiday-priority-${span.task.priority}`);
      if (span.task.completed)
        barEl.addClass("completed");
      const colWidth = 100 / 7;
      const left = span.startCol * colWidth;
      const width = (span.endCol - span.startCol + 1) * colWidth;
      const weekHeightPercent = 100 / 6;
      const rowOffsetPercent = rowIndex * 4 + 2;
      const topPercent = span.weekIndex * weekHeightPercent + rowOffsetPercent;
      barEl.style.cssText = `
				position: absolute;
				left: ${left}%;
				width: ${width}%;
				top: ${topPercent}%;
			`;
      barEl.addEventListener("click", (e) => {
        e.stopPropagation();
        this.toggleTask(span.task);
      });
    }
  }
  /**
   * 渲染单个日期格子
   *
   * 每个格子包含：
   * - 日期数字 + 农历信息
   * - 节假日标注（如 "春节"、"休"）
   * - 任务列表（带数量限制）
   * - "+N" 折叠提示 / "+" 新建按钮
   *
   * 格子的 CSS 类会根据日期类型自动添加：
   * - other-month: 非当月日期（灰色）
   * - today: 今天（高亮）
   * - holiday: 法定节假日
   * - workday: 调休上班日
   * - weekend / weekday
   */
  renderDayCell(day, tasks) {
    const cellEl = this.gridEl.createDiv("day-cell");
    if (!day.isCurrentMonth)
      cellEl.addClass("other-month");
    if (day.isToday)
      cellEl.addClass("today");
    const holidayInfo = holidayManager.getHolidayInfo(day.date);
    if (holidayInfo) {
      if (holidayInfo.type === "legal" /* LEGAL */)
        cellEl.addClass("holiday");
      else if (holidayInfo.type === "workday" /* WORKDAY */)
        cellEl.addClass("workday");
    } else if (day.isWeekend) {
      cellEl.addClass("weekend");
    } else {
      cellEl.addClass("weekday");
    }
    const headerEl = cellEl.createDiv("day-header");
    const headerRow = headerEl.createDiv("day-header-row");
    headerRow.createDiv("day-number").textContent = String(day.day);
    if (this.plugin.settings.showLunar) {
      const lunarInfo = getLunarInfo(day.date);
      const lunarEl = headerRow.createDiv("lunar-info");
      lunarEl.textContent = lunarInfo.text;
      if (isSpecialLunarDay(day.date) && !lunarInfo.isFestival)
        lunarEl.addClass("special-lunar");
    }
    if (this.plugin.settings.showHoliday && (holidayInfo == null ? void 0 : holidayInfo.type) === "legal" /* LEGAL */) {
      headerEl.createDiv("holiday-name").textContent = holidayInfo.name;
    }
    const tasksEl = cellEl.createDiv("day-tasks");
    const displayTasksList = this.plugin.settings.showCompletedTasks ? tasks : tasks.filter((t) => !t.completed);
    const limit = this.plugin.settings.tasksPerDayLimit;
    const displayTasks = displayTasksList.slice(0, limit);
    const remainingCount = displayTasksList.length - displayTasks.length;
    for (const task of displayTasks)
      this.renderTaskItem(tasksEl, task, day.date);
    if (remainingCount > 0)
      tasksEl.createDiv("more-tasks").textContent = `+${remainingCount}`;
    if (tasks.length === 0)
      tasksEl.createDiv("empty-hint").textContent = "+";
    cellEl.addEventListener("click", (e) => {
      if (e.target.closest(".task-item"))
        return;
      this.openCreateTaskModal(day.date, tasks);
    });
  }
  /**
   * 渲染单个任务项
   *
   * 显示格式：
   * - 单日任务：纯文本 + 优先级色块
   * - 跨天任务：文本 "(N天)" + 起止位置标记
   * - 已完成任务：删除线样式
   * - 逾期任务：红色警告
   */
  renderTaskItem(container, task, dayDate) {
    const taskEl = container.createDiv("task-item");
    if (task.completed)
      taskEl.addClass("completed");
    if (task.dueDate && isOverdue(task.dueDate) && !task.completed)
      taskEl.addClass("overdue");
    taskEl.addClass(`priority-bg-${task.priority}`);
    const multiDay = isMultiDayTask(task);
    if (multiDay) {
      taskEl.addClass("multi-day-task");
      taskEl.setAttribute("data-duration", String(getMultiDayDuration(task)));
      if (dayDate && task.startDate) {
        const start = new Date(task.startDate);
        const dayIndex = Math.floor((dayDate.getTime() - start.getTime()) / (1e3 * 60 * 60 * 24));
        taskEl.setAttribute("data-day-index", String(dayIndex));
        if (dayIndex === 0)
          taskEl.addClass("multi-day-start");
        if (dayDate.toISOString().split("T")[0] === task.dueDate)
          taskEl.addClass("multi-day-end");
      }
    }
    const contentEl = taskEl.createDiv("task-content");
    contentEl.textContent = multiDay ? `${task.content} (${getMultiDayDuration(task)}\u5929)` : task.content;
    contentEl.setAttribute("title", task.content);
    taskEl.addEventListener("click", (e) => {
      e.stopPropagation();
      this.toggleTask(task);
    });
  }
  /**
   * 切换任务完成状态
   *
   * 通过 TaskParser 修改文件内容，
   * 成功后显示通知并延迟 200ms 刷新视图。
   */
  async toggleTask(task) {
    const success = await this.taskParser.toggleTask(task);
    if (success) {
      new import_obsidian2.Notice(task.completed ? "\u4EFB\u52A1\u5DF2\u6807\u8BB0\u4E3A\u672A\u5B8C\u6210" : "\u4EFB\u52A1\u5DF2\u5B8C\u6210");
      setTimeout(() => this.refresh(), 200);
    } else {
      new import_obsidian2.Notice("\u64CD\u4F5C\u5931\u8D25\uFF0C\u8BF7\u91CD\u8BD5");
    }
  }
  /**
   * 打开创建任务弹窗
   *
   * @param date          - 点击的目标日期
   * @param existingTasks - 当天已有的任务列表（显示在弹窗中供参考）
   */
  openCreateTaskModal(date, existingTasks = []) {
    const modal = new CreateTaskModal(
      this.app,
      date,
      async (content, isAllDay, time, priority, endDate) => {
        const success = await this.taskParser.createTaskForDate(date, content, isAllDay, time, priority, endDate);
        if (success) {
          new import_obsidian2.Notice("\u4EFB\u52A1\u5DF2\u521B\u5EFA");
          await this.refresh(true);
        } else {
          new import_obsidian2.Notice("\u521B\u5EFA\u5931\u8D25\uFF0C\u8BF7\u91CD\u8BD5");
        }
      },
      this.plugin,
      existingTasks
    );
    modal.open();
  }
  /**
   * 导航到相邻月份
   *
   * @param direction - -1=上月, +1=下月
   */
  async navigateMonth(direction) {
    const target = direction < 0 ? getPrevMonth(this.currentYear, this.currentMonth) : getNextMonth(this.currentYear, this.currentMonth);
    this.currentYear = target.year;
    this.currentMonth = target.month;
    await this.renderCalendarGrid();
  }
  /**
   * 回到当前月
   */
  async goToToday() {
    const { year, month } = getCurrentYearMonth();
    this.currentYear = year;
    this.currentMonth = month;
    await this.renderCalendarGrid();
  }
};
var DatePickerModal = class {
  constructor(app, currentYear, currentMonth, onSubmit) {
    this.app = app;
    this.year = currentYear;
    this.month = currentMonth;
    this.onSubmit = onSubmit;
    const now = new Date();
    this.currentYear = now.getFullYear();
    this.currentMonth = now.getMonth();
  }
  /**
   * 显示弹窗
   *
   * 创建遮罩层 + 弹窗 DOM，绑定事件处理器。
   */
  open() {
    const overlay = document.createElement("div");
    overlay.className = "modal-overlay";
    document.body.appendChild(overlay);
    this.modalEl = document.createElement("div");
    this.modalEl.className = "date-picker-modal";
    const titleEl = this.modalEl.createDiv("modal-title");
    titleEl.textContent = "\u9009\u62E9\u65E5\u671F";
    const yearSection = this.modalEl.createDiv("picker-section");
    yearSection.createEl("div", { cls: "section-label", text: "\u5E74\u4EFD" });
    const yearInputWrapper = yearSection.createDiv("year-input-wrapper");
    const yearDecBtn = yearInputWrapper.createEl("button", { cls: "year-nav-btn", text: "\u2212" });
    const yearInput = yearInputWrapper.createEl("input", {
      cls: "year-input",
      attr: { type: "number", value: String(this.year), min: "1900", max: "2100" }
    });
    const yearIncBtn = yearInputWrapper.createEl("button", { cls: "year-nav-btn", text: "+" });
    const currentYearHint = yearSection.createEl("div", {
      cls: "current-year-hint",
      text: `\u5F53\u524D\u5E74\u4EFD: ${this.currentYear}`
    });
    yearDecBtn.addEventListener("click", () => {
      this.year = Math.max(1900, this.year - 1);
      yearInput.value = String(this.year);
    });
    yearIncBtn.addEventListener("click", () => {
      this.year = Math.min(2100, this.year + 1);
      yearInput.value = String(this.year);
    });
    yearInput.addEventListener("change", () => {
      let val = parseInt(yearInput.value);
      if (isNaN(val))
        val = this.currentYear;
      val = Math.max(1900, Math.min(2100, val));
      this.year = val;
      yearInput.value = String(val);
    });
    const monthSection = this.modalEl.createDiv("picker-section");
    monthSection.createEl("div", { cls: "section-label", text: "\u6708\u4EFD" });
    const monthGrid = monthSection.createDiv("month-grid");
    const monthNames = ["1\u6708", "2\u6708", "3\u6708", "4\u6708", "5\u6708", "6\u6708", "7\u6708", "8\u6708", "9\u6708", "10\u6708", "11\u6708", "12\u6708"];
    for (let m = 0; m < 12; m++) {
      const isSelected = m === this.month;
      const isCurrent = m === this.currentMonth;
      const monthBtn = monthGrid.createEl("button", {
        cls: `month-btn ${isSelected ? "selected" : ""} ${isCurrent ? "current" : ""}`,
        text: monthNames[m]
      });
      monthBtn.addEventListener("click", () => {
        monthGrid.querySelectorAll(".month-btn").forEach((btn) => btn.removeClass("selected"));
        monthBtn.addClass("selected");
        this.month = m;
      });
    }
    const btnGroup = this.modalEl.createDiv("modal-buttons");
    const cancelBtn = btnGroup.createEl("button", { cls: "btn-cancel", text: "\u53D6\u6D88" });
    cancelBtn.addEventListener("click", () => this.close(overlay));
    const confirmBtn = btnGroup.createEl("button", { cls: "btn-confirm", text: "\u786E\u5B9A" });
    confirmBtn.addEventListener("click", () => {
      this.onSubmit(this.year, this.month);
      this.close(overlay);
    });
    document.body.appendChild(this.modalEl);
    overlay.addEventListener("click", () => this.close(overlay));
  }
  /**
   * 关闭弹窗并清理 DOM
   */
  close(overlay) {
    overlay.remove();
    this.modalEl.remove();
  }
};
var CreateTaskModal = class {
  constructor(app, date, onSubmit, plugin, existingTasks = []) {
    this.app = app;
    this.date = date;
    this.onSubmit = onSubmit;
    this.plugin = plugin;
    this.existingTasks = existingTasks;
  }
  /**
   * 显示弹窗
   */
  open() {
    const overlay = document.createElement("div");
    overlay.className = "modal-overlay";
    document.body.appendChild(overlay);
    this.modalEl = document.createElement("div");
    this.modalEl.className = "create-task-modal";
    const dateInfoEl = this.modalEl.createDiv("modal-date-info");
    const weekday = ["\u5468\u65E5", "\u5468\u4E00", "\u5468\u4E8C", "\u5468\u4E09", "\u5468\u56DB", "\u5468\u4E94", "\u5468\u516D"][this.date.getDay()];
    const holidayInfo = holidayManager.getHolidayInfo(this.date);
    const holidayText = holidayInfo ? ` \xB7 ${holidayInfo.name}` : "";
    dateInfoEl.innerHTML = `<div class="date-main">${this.date.getMonth() + 1}\u6708${this.date.getDate()}\u65E5 \xB7 ${weekday}${holidayText}</div>`;
    if (this.existingTasks.length > 0) {
      const existingTasksEl = this.modalEl.createDiv("modal-existing-tasks");
      existingTasksEl.createEl("div", { cls: "existing-tasks-title", text: `\u4ECA\u65E5\u5DF2\u6709 ${this.existingTasks.length} \u4E2A\u4EFB\u52A1` });
      const tasksListEl = existingTasksEl.createDiv("existing-tasks-list");
      this.existingTasks.slice(0, 5).forEach((task) => {
        const taskEl = tasksListEl.createDiv("existing-task-item");
        if (task.completed)
          taskEl.addClass("completed");
        if (task.priority > 0)
          taskEl.addClass(`priority-${task.priority}`);
        taskEl.textContent = task.content;
      });
      if (this.existingTasks.length > 5) {
        tasksListEl.createDiv("existing-tasks-more").textContent = `\u8FD8\u6709 ${this.existingTasks.length - 5} \u4E2A\u4EFB\u52A1...`;
      }
    }
    const inputWrapper = this.modalEl.createDiv("task-input-wrapper");
    const inputEl = inputWrapper.createEl("input", {
      cls: "task-input",
      attr: { type: "text", placeholder: "\u8F93\u5165\u4EFB\u52A1\u5185\u5BB9..." }
    });
    let timeInputEl = null;
    let isAllDay = this.plugin.settings.defaultAllDayTask;
    if (!this.plugin.settings.defaultAllDayTask) {
      const timeContainer = this.modalEl.createDiv("modal-time-container");
      timeContainer.createEl("span", { cls: "time-label", text: "\u65F6\u95F4" });
      const timeWrapper = timeContainer.createDiv("time-input-wrapper");
      timeInputEl = timeWrapper.createEl("input", {
        cls: "time-input",
        attr: { type: "time", value: "09:00" }
      });
      const allDayToggle = timeWrapper.createDiv("all-day-toggle");
      const allDayCheckbox = allDayToggle.createEl("input", { attr: { type: "checkbox" } });
      allDayToggle.createEl("span", { text: "\u5168\u5929" });
      allDayCheckbox.addEventListener("change", (e) => {
        isAllDay = e.target.checked;
        if (timeInputEl) {
          timeInputEl.disabled = isAllDay;
          timeInputEl.style.opacity = isAllDay ? "0.4" : "1";
        }
      });
    }
    const endDateContainer = this.modalEl.createDiv("modal-end-date");
    endDateContainer.createEl("span", { cls: "end-date-label", text: "\u7ED3\u675F\u65E5\u671F" });
    const endDateWrapper = endDateContainer.createDiv("end-date-wrapper");
    let endDate = void 0;
    let isMultiDay = false;
    const multiDayToggle = endDateWrapper.createDiv("multi-day-toggle");
    const multiDayCheckbox = multiDayToggle.createEl("input", { attr: { type: "checkbox" } });
    multiDayToggle.createEl("span", { text: "\u8DE8\u5929\u4EFB\u52A1" });
    const endDateInput = endDateWrapper.createEl("input", {
      cls: "end-date-input",
      attr: { type: "date", value: this.formatDateForInput(this.date), min: this.formatDateForInput(this.date) }
    });
    endDateInput.style.display = "none";
    multiDayCheckbox.addEventListener("change", (e) => {
      isMultiDay = e.target.checked;
      endDateInput.style.display = isMultiDay ? "block" : "none";
      if (isMultiDay) {
        endDate = new Date(endDateInput.value);
      } else {
        endDate = void 0;
      }
    });
    endDateInput.addEventListener("change", (e) => {
      if (isMultiDay) {
        endDate = new Date(e.target.value);
      }
    });
    const priorityContainer = this.modalEl.createDiv("modal-priority");
    priorityContainer.createEl("span", { cls: "priority-label", text: "\u4F18\u5148\u7EA7" });
    const priorityGroup = priorityContainer.createDiv("priority-group");
    const priorities = [
      { value: 3, class: "priority-high", label: "\u9AD8" },
      { value: 2, class: "priority-medium", label: "\u4E2D" },
      { value: 0, class: "priority-none", label: "\u666E\u901A" }
    ];
    let selectedPriority = 0;
    const priorityWrappers = [];
    priorities.forEach((p, index) => {
      const wrapper = priorityGroup.createDiv("priority-btn-wrapper");
      if (p.value === 0)
        wrapper.addClass("selected");
      const btn = wrapper.createEl("button", {
        cls: `priority-btn ${p.class} ${p.value === 0 ? "selected" : ""}`
      });
      wrapper.createDiv("priority-btn-text").textContent = p.label;
      priorityWrappers.push(wrapper);
      wrapper.addEventListener("click", () => {
        selectedPriority = p.value;
        priorityWrappers.forEach((w) => {
          var _a;
          w.removeClass("selected");
          (_a = w.querySelector(".priority-btn")) == null ? void 0 : _a.removeClass("selected");
        });
        wrapper.addClass("selected");
        btn.addClass("selected");
      });
    });
    const btnGroup = this.modalEl.createDiv("modal-buttons");
    const cancelBtn = btnGroup.createEl("button", { cls: "btn-cancel", text: "\u53D6\u6D88" });
    cancelBtn.addEventListener("click", () => this.close(overlay));
    const confirmBtn = btnGroup.createEl("button", { cls: "btn-confirm", text: "\u6DFB\u52A0\u4EFB\u52A1" });
    const submitTask = () => {
      const content = inputEl.value.trim();
      if (content) {
        const time = timeInputEl && !isAllDay ? timeInputEl.value : void 0;
        this.onSubmit(content, isAllDay, time, selectedPriority, endDate);
        this.close(overlay);
      }
    };
    confirmBtn.addEventListener("click", submitTask);
    setTimeout(() => {
      inputEl.focus();
    }, 100);
    inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        submitTask();
      else if (e.key === "Escape")
        this.close(overlay);
    });
    document.body.appendChild(this.modalEl);
    overlay.addEventListener("click", () => this.close(overlay));
  }
  /**
   * 关闭弹窗并清理 DOM
   */
  close(overlay) {
    overlay.remove();
    this.modalEl.remove();
  }
  /**
   * 格式化 Date 对象为 HTML date input 所需的格式
   */
  formatDateForInput(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  completedTaskStyle: "strike",
  defaultAllDayTask: true,
  firstDayOfWeek: 0,
  // 周日起始
  showLunar: true,
  showHoliday: true,
  tasksPerDayLimit: 5,
  highPriorityColor: "#ef4444",
  mediumPriorityColor: "#f59e0b"
};
var MonthlyTasksPlugin = class extends import_obsidian3.Plugin {
  /**
   * 插件加载入口（Obsidian 自动调用）
   *
   * 执行顺序：
   * 1. 加载用户设置（合并默认值）
   * 2. 初始化任务解析器
   * 3. 注册自定义视图、Ribbon 图标、命令
   * 4. 注册设置选项卡
   * 5. 绑定文件监听事件
   */
  async onload() {
    await this.loadSettings();
    const { holidayManager: holidayManager2 } = await Promise.resolve().then(() => (init_HolidayManager(), HolidayManager_exports));
    holidayManager2.updateFromNetwork(new Date().getFullYear()).catch(() => {
    });
    this.taskParser = new TaskParser(this.app);
    this.registerView(
      VIEW_TYPE_MONTHLY,
      (leaf) => new MonthlyView(leaf, this.taskParser, this)
    );
    this.addRibbonIcon("calendar", "\u6708\u5386\u4EFB\u52A1", () => this.activateView());
    this.addCommand({ id: "open-monthly-view", name: "\u6253\u5F00\u6708\u5386\u4EFB\u52A1\u89C6\u56FE", callback: () => this.activateView() });
    this.addCommand({ id: "refresh-monthly-view", name: "\u5237\u65B0\u6708\u5386\u4EFB\u52A1\u89C6\u56FE", callback: () => this.refreshView() });
    this.addSettingTab(new MonthlyTasksSettingTab(this.app, this));
    const refreshDebounced = this.debounce(() => this.refreshView(), 300);
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (file instanceof import_obsidian3.TFile && file.extension === "md") {
        this.taskParser.invalidateCache();
        refreshDebounced();
      }
    }));
    this.registerEvent(this.app.vault.on("create", (file) => {
      if (file instanceof import_obsidian3.TFile && file.extension === "md") {
        this.taskParser.invalidateCache();
        refreshDebounced();
      }
    }));
    this.registerEvent(this.app.vault.on("delete", () => {
      this.taskParser.invalidateCache();
      refreshDebounced();
    }));
    this.registerEvent(this.app.vault.on("rename", () => {
      this.taskParser.invalidateCache();
      refreshDebounced();
    }));
  }
  /**
   * 防抖工具函数
   *
   * 将多次连续调用合并为一次执行，适用于高频事件处理。
   * 例如：快速保存多个文件时不会触发多次渲染。
   *
   * @typeParam T - 函数类型
   * @param fn    - 需要防抖的目标函数
   * @param delay - 延迟时间（毫秒）
   * @returns 包装后的防抖函数
   */
  debounce(fn, delay) {
    let timer = null;
    return (...args) => {
      if (timer)
        window.clearTimeout(timer);
      timer = window.setTimeout(() => fn(...args), delay);
    };
  }
  /**
   * 从 data.json 加载用户设置
   *
   * 使用 `Object.assign` 合并默认值，确保新增设置项有合理的初始值。
   */
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * 保存当前设置到 data.json
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * 激活/打开月历视图
   *
   * 如果已有打开的视图则聚焦它，
   * 否则在右侧面板新建一个视图标签页。
   */
  async activateView() {
    const { workspace } = this.app;
    const existingLeaf = workspace.getLeavesOfType(VIEW_TYPE_MONTHLY)[0];
    if (existingLeaf) {
      workspace.revealLeaf(existingLeaf);
      return;
    }
    const leaf = workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({ type: VIEW_TYPE_MONTHLY });
      workspace.revealLeaf(leaf);
    }
  }
  /**
   * 刷新所有打开的月历视图
   *
   * 遍历所有月历视图实例，触发重新渲染。
   *
   * @param force - 是否强制完全重建 DOM（true=重建整个视图，false=仅更新数据）
   */
  async refreshView(force = false) {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_MONTHLY);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof MonthlyView) {
        await view.refresh(force);
      }
    }
  }
};
var MonthlyTasksSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /**
   * 渲染设置界面
   *
   * 每次打开设置页面时会重新调用此方法。
   * 使用 Obsidian 的 Setting API 构建表单控件。
   */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const tipEl = containerEl.createDiv("setting-item-description mt-settings-tip");
    tipEl.innerHTML = `
			<div class="mt-settings-text">
				\u70B9\u51FB\u6708\u5386\u65E5\u671F\u521B\u5EFA\u4EFB\u52A1 \xB7 \u6570\u636E\u81EA\u52A8\u5B58\u5165 <code>\u4EFB\u52A1/</code> \u76EE\u5F55 \xB7 Ctrl/Cmd+P \u641C\u7D22\u300C\u6708\u5386\u4EFB\u52A1\u300D\xB7 Markdown \u683C\u5F0F\uFF0C\u517C\u5BB9 Obsidian Tasks \u63D2\u4EF6
			</div>
		`;
    containerEl.createEl("h2", { text: "\u663E\u793A\u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("\u5DF2\u5B8C\u6210\u4EFB\u52A1\u663E\u793A\u65B9\u5F0F").setDesc("\u6708\u5386\u4E2D\u5DF2\u5B8C\u6210\u7684\u4EFB\u52A1\u5982\u4F55\u5C55\u793A").setClass("mt-completed-style-setting");
    {
      const styleSetting = containerEl.querySelector(".mt-completed-style-setting");
      if (styleSetting) {
        const ctrl = styleSetting.createDiv("mt-segmented-control");
        const options = [
          { value: "strike", label: "\u5E26\u5220\u9664\u7EBF", desc: "\u4FDD\u7559\u5728\u5217\u8868\u4E2D\uFF0C\u52A0\u5220\u9664\u7EBF\u6807\u8BB0" },
          { value: "normal", label: "\u6B63\u5E38\u663E\u793A", desc: "\u548C\u672A\u5B8C\u6210\u4EFB\u52A1\u4E00\u6837\u6B63\u5E38\u663E\u793A" },
          { value: "hide", label: "\u9690\u85CF\u4E0D\u663E\u793A", desc: "\u4ECE\u6708\u5386\u89C6\u56FE\u4E2D\u5B8C\u5168\u9690\u85CF" }
        ];
        options.forEach((opt) => {
          const btn = ctrl.createEl("button", {
            type: "button",
            text: opt.label,
            cls: `mt-seg-btn${this.plugin.settings.completedTaskStyle === opt.value ? " selected" : ""}`
          });
          btn.dataset.value = opt.value;
          btn.setAttribute("aria-label", opt.desc);
          btn.addEventListener("click", async () => {
            this.plugin.settings.completedTaskStyle = opt.value;
            await this.plugin.saveSettings();
            ctrl.querySelectorAll(".mt-seg-btn").forEach((b) => b.classList.remove("selected"));
            btn.classList.add("selected");
            this.plugin.refreshView();
          });
        });
      }
    }
    new import_obsidian3.Setting(containerEl).setName("\u663E\u793A\u519C\u5386").setDesc("\u65E5\u671F\u4E0B\u65B9\u663E\u793A\u519C\u5386\u548C\u8282\u6C14").addToggle((toggle) => toggle.setValue(this.plugin.settings.showLunar).onChange(async (value) => {
      this.plugin.settings.showLunar = value;
      await this.plugin.saveSettings();
      this.plugin.refreshView();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u663E\u793A\u8282\u5047\u65E5").setDesc("\u6807\u6CE8\u6CD5\u5B9A\u8282\u5047\u65E5\u548C\u8C03\u4F11").addToggle((toggle) => toggle.setValue(this.plugin.settings.showHoliday).onChange(async (value) => {
      this.plugin.settings.showHoliday = value;
      await this.plugin.saveSettings();
      this.plugin.refreshView();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u5237\u65B0\u8282\u5047\u65E5\u6570\u636E").setDesc("\u4ECE\u7F51\u7EDC\u91CD\u65B0\u83B7\u53D6\u5F53\u5E74\u8282\u5047\u65E5\u4FE1\u606F").addButton((button) => button.setButtonText("\u5237\u65B0").onClick(async () => {
      button.buttonEl.textContent = "\u5237\u65B0\u4E2D...";
      button.buttonEl.disabled = true;
      try {
        const { holidayManager: holidayManager2 } = await Promise.resolve().then(() => (init_HolidayManager(), HolidayManager_exports));
        await holidayManager2.updateFromNetwork(new Date().getFullYear());
        this.plugin.refreshView();
        new Notice("\u8282\u5047\u65E5\u6570\u636E\u5DF2\u5237\u65B0");
      } catch (e) {
        new Notice("\u5237\u65B0\u5931\u8D25: " + e.message);
      }
      button.buttonEl.textContent = "\u5237\u65B0";
      button.buttonEl.disabled = false;
    }));
    containerEl.createEl("h2", { text: "\u4EFB\u52A1\u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("\u9ED8\u8BA4\u5168\u5929\u4EFB\u52A1").setDesc("\u65B0\u5EFA\u4EFB\u52A1\u9ED8\u8BA4\u4E0D\u5E26\u5177\u4F53\u65F6\u95F4").addToggle((toggle) => toggle.setValue(this.plugin.settings.defaultAllDayTask).onChange(async (value) => {
      this.plugin.settings.defaultAllDayTask = value;
      await this.plugin.saveSettings();
      this.plugin.refreshView();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u6BCF\u5468\u7B2C\u4E00\u5929").setDesc("\u65E5\u5386\u6BCF\u5468\u8D77\u59CB\u65E5").addDropdown((dropdown) => dropdown.addOption("1", "\u5468\u4E00").addOption("0", "\u5468\u65E5").setValue(String(this.plugin.settings.firstDayOfWeek)).onChange(async (value) => {
      this.plugin.settings.firstDayOfWeek = parseInt(value);
      await this.plugin.saveSettings();
      this.plugin.refreshView();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u6BCF\u65E5\u4EFB\u52A1\u663E\u793A\u6570\u91CF").setDesc("\u6BCF\u4E2A\u65E5\u671F\u683C\u5B50\u6700\u591A\u663E\u793A\u7684\u4EFB\u52A1\u6570").addDropdown((dropdown) => dropdown.addOption("3", "3\u4E2A").addOption("4", "4\u4E2A").addOption("5", "5\u4E2A").addOption("6", "6\u4E2A").addOption("7", "7\u4E2A").addOption("8", "8\u4E2A").addOption("9", "9\u4E2A").addOption("10", "10\u4E2A").setValue(String(this.plugin.settings.tasksPerDayLimit)).onChange(async (value) => {
      this.plugin.settings.tasksPerDayLimit = parseInt(value);
      await this.plugin.saveSettings();
      this.plugin.refreshView();
    }));
  }
};
/**
 * =============================================================================
 * obsidian-monthly-tasks - 插件主入口
 * =============================================================================
 *
 * 滴答清单风格的 Obsidian 月视图任务管理插件。
 * 提供月历网格视图，支持农历、节假日显示、任务创建与管理。
 *
 * @author  duany
 * @version 1.2.0
 * @license MIT
 * @see     https://github.com/duanydev/obsidian-monthly-tasks
 */
